import os
import certifi

# Teilt OpenSSL mit, wo die Zertifikate von 'certifi' liegen
os.environ['SSL_CERT_FILE'] = certifi.where()

# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOz3bbG3JNkorHr5flsO-gwQP6DWKDMa
"""

!yes | buildozer android p4a -- accept-sdk-license

!yes | buildozer android p4a -- accept-sdk-license

import kivy
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.uix.textinput import TextInput
from kivy.uix.scrollview import ScrollView
from kivy.uix.togglebutton import ToggleButton
from kivy.metrics import dp, sp
from kivy.clock import Clock
from kivy.utils import get_color_from_hex
import random, secrets, requests, threading, time, webbrowser, json, os
from datetime import datetime

# --- DESIGN-KONSTANTEN ---
CLR_BG = get_color_from_hex("#020617")
CLR_CARD = get_color_from_hex("#0f172a")
CLR_ACCENT = get_color_from_hex("#22d3ee")
CLR_GOLD = get_color_from_hex("#fbbf24")
CLR_RED = get_color_from_hex("#f43f5e")

LOTTO_PRESETS = {
    "EUROJACKPOT": ["50", "50", "50", "50", "50", "12", "12"],
    "6aus49": ["49", "49", "49", "49", "49", "49", "10"],
    "FREIHEIT+": ["38", "38", "38", "38", "38", "38", "38"],
    "GLÜCKSSPIRALE": ["9", "9", "9", "9", "9", "9", "9"]
}

# --- GLOBALE STRUKTUR ---
SPENDEN_PROJEKTE = {
    "GLOBAL": [
        ("WWF Meeresschildkröten", "https://www.wwf.de/themen-projekte/bedrohte-tier-und-pflanzenarten/meeresschildkroeten"),
        ("Plan International", "https://www.plan.de/jetzt-spenden.html"),
        ("Pomoziba", "https://pomoziba.org"),
        ("UNICEF", "https://www.unicef.de/spenden")
    ],
    "NATIONAL (DE)": [
        ("NABU Deutschland", "https://www.nabu.de/spenden-und-mitmachen/index.html"),
        ("DKMS Registrierung", "https://www.dkms.de/aktiv-werden"),
        ("Deutsche Krebshilfe", "https://www.krebshilfe.de/helfen/spenden/"),
        ("Johanniter Notfallhilfe", "https://www.johanniter.de/spenden")
    ],
    "LOKAL (Augsburg)": [
        ("Zoo Augsburg", "https://www.zoo-augsburg.com/zoo-unterstuetzen/spenden/"),
        ("Bunter Kreis Augsburg", "https://www.bunter-kreis.de/spenden-helfen/"),
        ("Tierheim Augsburg", "https://www.tierheim-augsburg.de/helfen/spenden/"),
        ("Fuggerei Augsburg", "https://www.fuggerei.de/stiftung/spenden-helfen")
    ]
}

CONFIG_FILE = "lotto_config.json"

class QuantumLottoKarmaApp(App):
    def build(self):
        self.is_drawing = False
        self.current_region = "GLOBAL"

        self.root = BoxLayout(orientation='vertical', padding=dp(20), spacing=dp(10))

        # 1. HEADER
        header = BoxLayout(size_hint_y=None, height=dp(50))
        header.add_widget(Label(text="QUANTUM LOTTO", font_size=sp(22), bold=True, color=CLR_ACCENT))
        self.expert_btn = ToggleButton(text="EXPERT MODE", size_hint_x=None, width=dp(100),
                                       background_color=CLR_CARD, color=CLR_GOLD,
                                       font_size=sp(10), on_press=self.toggle_expert)
        header.add_widget(self.expert_btn)
        self.root.add_widget(header)

        # 2. NEU: REGIONEN-AUSWAHL
        region_label = Label(text="WÄHLE DEINE KARMA-REGION:", font_size=sp(10), color=CLR_GOLD, size_hint_y=None, height=dp(20))
        self.root.add_widget(region_label)

        region_box = BoxLayout(size_hint_y=None, height=dp(35), spacing=dp(5))
        for r_name in SPENDEN_PROJEKTE.keys():
            btn = ToggleButton(text=r_name, group="region",
                               state="down" if r_name == "GLOBAL" else "normal",
                               font_size=sp(9), background_color=CLR_CARD)
            btn.bind(on_press=lambda x, n=r_name: self.set_region(n))
            region_box.add_widget(btn)
        self.root.add_widget(region_box)

        # 3. PRESETS
        preset_box = BoxLayout(size_hint_y=None, height=dp(40), spacing=dp(5))
        for name in LOTTO_PRESETS.keys():
            btn = Button(text=name, font_size=sp(9), background_color=CLR_CARD, bold=True,
                         on_press=lambda x, n=name: self.apply_preset(n))
            preset_box.add_widget(btn)
        self.root.add_widget(preset_box)

        # 4. EXPERTEN-BEREICH
        self.expert_section = BoxLayout(orientation='vertical', size_hint_y=None, height=0, opacity=0)
        self.expert_scroll = ScrollView(bar_width=dp(8))
        self.expert_grid = GridLayout(cols=1, spacing=dp(8), size_hint_y=None, padding=[dp(35), 0, dp(35), 0],
                                      row_default_height=dp(45), row_force_default=True)
        self.expert_grid.bind(minimum_height=self.expert_grid.setter('height'))

        self.config_entries = []
        saved_data = self.load_settings()
        for i in range(7):
            row = BoxLayout(orientation='horizontal', spacing=dp(15))
            lbl = Label(text=f"{i+1}", size_hint_x=None, width=dp(25), color=CLR_ACCENT, bold=True)
            val = saved_data[i] if i < len(saved_data) else "50"
            ti = TextInput(text=val, multiline=False, font_size=sp(15), background_color=(0.1, 0.15, 0.25, 1),
                           foreground_color=CLR_GOLD)
            row.add_widget(lbl)
            row.add_widget(ti)
            self.config_entries.append(ti)
            self.expert_grid.add_widget(row)

        self.expert_scroll.add_widget(self.expert_grid)
        self.expert_section.add_widget(self.expert_scroll)
        self.root.add_widget(self.expert_section)

        self.dynamic_spacer = Label(text="", size_hint_y=1)
        self.root.add_widget(self.dynamic_spacer)

        # 5. KUGEL-DISPLAY
        self.ball_layout = BoxLayout(orientation='vertical', size_hint_y=None, height=dp(110), spacing=dp(5))
        ball_row = BoxLayout(spacing=dp(5))
        self.ball_labels = []
        for _ in range(7):
            lbl = Label(text="?", font_size=sp(24), bold=True, color=(0.3, 0.3, 0.3, 1))
            self.ball_labels.append(lbl)
            ball_row.add_widget(lbl)

        self.status_label = Label(text="Wähle eine Region für dein Karma.", font_size=sp(13), color=CLR_ACCENT, italic=True)
        self.ball_layout.add_widget(ball_row)
        self.ball_layout.add_widget(self.status_label)
        self.root.add_widget(self.ball_layout)

        # 6. HISTORIE
        self.hist_scroll = ScrollView(size_hint_y=0.15)
        self.hist_label = Label(text="", size_hint_y=None, halign='center', font_size=sp(14), color=(0.4, 0.4, 0.4, 1))
        self.hist_label.bind(texture_size=self.hist_label.setter('size'))
        self.hist_scroll.add_widget(self.hist_label)
        self.root.add_widget(self.hist_scroll)

        # 7. AKTION-BUTTONS
        btn_row = BoxLayout(size_hint_y=None, height=dp(70), spacing=dp(15))
        self.draw_btn = Button(text="START", background_color=get_color_from_hex("#0e7490"), font_size=sp(18), bold=True)
        self.draw_btn.bind(on_press=self.start_draw)

        karma_btn = Button(text="KARMA", background_color=CLR_RED, font_size=sp(18), bold=True)
        karma_btn.bind(on_press=self.open_karma)

        btn_row.add_widget(self.draw_btn)
        btn_row.add_widget(karma_btn)
        self.root.add_widget(btn_row)

        return self.root

    def set_region(self, name):
        self.current_region = name
        self.status_label.text = f"Region eingestellt auf: {name}"

    def open_karma(self, instance):
        projekte = SPENDEN_PROJEKTE[self.current_region]
        project = random.choice(projekte)
        self.status_label.text = f"Impuls ({self.current_region}): {project[0]}"
        webbrowser.open(project[1])

    def toggle_expert(self, instance):
        if instance.state == 'down':
            self.expert_section.height = dp(250)
            self.expert_section.opacity = 1
            self.dynamic_spacer.size_hint_y = 0.05
        else:
            self.expert_section.height = 0
            self.expert_section.opacity = 0
            self.dynamic_spacer.size_hint_y = 1

    def apply_preset(self, name):
        for i, v in enumerate(LOTTO_PRESETS[name]):
            self.config_entries[i].text = v

    def save_settings(self):
        try:
            with open(CONFIG_FILE, "w") as f: json.dump([ti.text for ti in self.config_entries], f)
        except: pass

    def load_settings(self):
        if os.path.exists(CONFIG_FILE):
            try:
                with open(CONFIG_FILE, "r") as f: return json.load(f)
            except: return []
        return []

    def start_draw(self, *args):
        if not self.is_drawing:
            self.save_settings()
            threading.Thread(target=self.run_logic).start()

    def run_logic(self):
        self.is_drawing = True
        self.draw_btn.disabled = True
        final = []; used = set()
        for i in range(7):
            raw = self.config_entries[i].text
            pool = [int(x.strip()) for x in raw.replace(";", ",").split(",") if x.strip().isdigit()] if ("," in raw or ";" in raw) else list(range(1, (int(raw) if raw.isdigit() else 50)+1))
            avail = [n for n in pool if n not in used] or pool

            for _ in range(5):
                Clock.schedule_once(lambda dt, idx=i, v=random.choice(avail): self.update_ball(idx, str(v)))
                time.sleep(0.05)

            res = self.get_q(avail)
            final.append(res)

            if i < 6 and self.config_entries[i].text == self.config_entries[i+1].text: used.add(res)
            else: used = set()

            Clock.schedule_once(lambda dt, idx=i, v=res: self.update_ball(idx, str(v), True))
            time.sleep(0.1)

        Clock.schedule_once(lambda dt: self.add_hist(f"{datetime.now().strftime('%H:%M')} | {' . '.join(map(str, final))}"))
        self.is_drawing = False
        self.draw_btn.disabled = False

    def get_q(self, pool):
        try:
             # Nutze deinen neuen API-Key für die offizielle v1 Schnittstelle
            api_key = "BfPlcBrXfz5JKtQs0nlTN7OBJx2nGsuI5WUaKtvR"
            url = f"https://quantumnumbers.anu.edu.au/api/v1/random?length=1&type=uint8&apiKey={api_key}"
            r = requests.get(url, timeout=2.5)

            return pool[r.json()['data'][0] % len(pool)]
        except: return secrets.choice(pool)

    def update_ball(self, idx, v, final=False):
        self.ball_labels[idx].text = str(v)
        if final: self.ball_labels[idx].color = CLR_ACCENT if idx < 5 else CLR_GOLD
        else: self.ball_labels[idx].color = (0.3, 0.3, 0.3, 1)

    def add_hist(self, line):
        self.hist_label.text = line + "\n" + self.hist_label.text

if __name__ == '__main__':
    QuantumLottoKarmaApp().run()

"""# Neuer Abschnitt"""

!buildozer -v android debug

!pip install buildozer cython
!apt-get install -y python3-dev libffi-dev libssl-dev build-essential
!apt-get install -y libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
!apt-get install -y zlib1g-dev openjdk-17-jdk zip unzip
!apt-get install -y aidl autoconf automake libtool pkg-config

!buildozer init

import os
if os.path.exists('buildozer.spec'):
    with open('buildozer.spec', 'r') as f:
        spec = f.read()
    spec = spec.replace('requirements = python3,kivy', 'requirements = python3,kivy,requests,urllib3')
    spec = spec.replace('#android.permissions = INTERNET', 'android.permissions = INTERNET')
    with open('buildozer.spec', 'w') as f:
        f.write(spec)
    print('buildozer.spec wurde erfolgreich aktualisiert.')

!yes | buildozer -v android debug

!yes | buildozer android p4a -- sdk-tools/sdkmanager --licenses

import os

# --- DEINE EINSTELLUNGEN ---
NEUER_TITEL = "Lotto Global Quantum Karma 2026"
NEUER_PAKETNAME = "lotto_global_2026"
# ---------------------------

if os.path.exists('buildozer.spec'):
    with open('buildozer.spec', 'r') as f:
        lines = f.readlines()

    with open('buildozer.spec', 'w') as f:
        for line in lines:
            if line.startswith('title ='):
                f.write(f'title = {NEUER_TITEL}\n')
            elif line.startswith('package.name ='):
                f.write(f'package.name = {NEUER_PAKETNAME}\n')
            else:
                f.write(line)

    print(f'Erfolgreich umbenannt in: {NEUER_TITEL} ({NEUER_PAKETNAME})')
    print('Starte nun die Build-Zelle erneut, um die neue APK zu erzeugen.')
else:
    print('buildozer.spec nicht gefunden!')

from google.colab import files
import os

# Suche nach der APK im bin-Ordner
bin_path = 'bin/'
if os.path.exists(bin_path):
    apks = [f for f in os.listdir(bin_path) if f.endswith('.apk')]
    if apks:
        print(f'Lade {apks[0]} herunter...')
        files.download(os.path.join(bin_path, apks[0]))
    else:
        print('Keine APK-Datei im bin-Ordner gefunden. Läuft der Build noch?')
else:
    print('Der bin-Ordner existiert noch nicht.')

kivy_code = r'''import kivy
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.uix.textinput import TextInput
from kivy.uix.togglebutton import ToggleButton
from kivy.metrics import dp, sp
from kivy.clock import Clock
from kivy.utils import get_color_from_hex
from kivy.core.window import Window
import random, secrets, requests, threading, time, webbrowser, json, os
from datetime import datetime

# --- DESIGN ---
CLR_CARD = get_color_from_hex("#0f172a")
CLR_ACCENT = get_color_from_hex("#22d3ee")
CLR_ACTIVE = get_color_from_hex("#0e7490")
CLR_GOLD = get_color_from_hex("#fbbf24")
CLR_GREEN = get_color_from_hex("#22c55e")
CLR_RED = get_color_from_hex("#f43f5e")

LOTTO_PRESETS = {
    "6aus49": ["49", "49", "49", "49", "49", "49", "10"],
    "EUROJACKPOT": ["50", "50", "50", "50", "50", "12", "12"],
    "FREIHEIT+": ["38", "38", "38", "38", "38", "38", "38"],
    "GLÜCKSSPIRALE": ["9", "9", "9", "9", "9", "9", "9"]
}

# --- HERZSTÜCK: 26 ORGANISATIONEN ---
SPENDEN_PROJEKTE = {
    "GLOBAL": [("UNICEF", "https://www.unicef.de"), ("WWF", "https://www.wwf.de"), ("Ärzte ohne Grenzen", "https://www.aerzte-ohne-grenzen.de"), ("Plan International", "https://www.plan.de"), ("Save the Children", "https://www.savethechildren.de"), ("Oxfam", "https://www.oxfam.de"), ("Greenpeace", "https://www.greenpeace.de"), ("Amnesty International", "https://www.amnesty.de")],
    "NATIONAL": [("NABU", "https://www.nabu.de"), ("DKMS", "https://www.dkms.de"), ("Deutsche Krebshilfe", "https://www.krebshilfe.de"), ("DRK", "https://www.drk.de"), ("Weisser Ring", "https://www.weisser-ring.de"), ("Die Arche", "https://www.kinderprojekt-arche.de"), ("Johanniter", "https://www.johanniter.de"), ("Malteser", "https://www.malteser.de"), ("BUND", "https://www.bund.net")],
    "AUGSBURG": [("Zoo Augsburg", "https://www.zoo-augsburg.com"), ("Tierheim", "https://www.tierheim-augsburg.de"), ("Kartei Not", "https://www.kartei-der-not.de"), ("Bunter Kreis", "https://www.bunter-kreis.de"), ("SKM Augsburg", "https://www.skm-augsburg.de"), ("Puppenkiste", "https://www.augsburger-puppenkiste.de"), ("Hospiz Augsburg", "https://www.hospiz-augsburg.de"), ("Augsburger Tafel", "https://www.augsburger-tafel.de"), ("Fuggerei", "https://www.fuggerei.de")]
}

class QuantumLottoKarmaApp(App):
    def build(self):
        self.is_drawing = False
        self.current_region = "GLOBAL"
        self.current_preset = "6aus49"
        self.quantum_success = False

        self.root = BoxLayout(orientation='vertical', padding=dp(15), spacing=dp(10))

        # 1. HEADER
        header = BoxLayout(size_hint_y=None, height=dp(50))
        header.add_widget(Label(text="QUANTUM LOTTO", font_size=sp(22), bold=True, color=CLR_ACCENT))
        self.expert_btn = ToggleButton(text="EXPERT", size_hint_x=None, width=dp(80), background_color=CLR_CARD, color=CLR_GOLD)
        self.expert_btn.bind(on_release=self.toggle_expert)
        header.add_widget(self.expert_btn)
        self.root.add_widget(header)

        # 2. REGIONEN
        region_grid = GridLayout(cols=3, size_hint_y=None, height=dp(40), spacing=dp(5))
        self.reg_btns = {}
        for r_name in SPENDEN_PROJEKTE.keys():
            btn = ToggleButton(text=r_name, group="region", state="down" if r_name == "GLOBAL" else "normal", background_color=CLR_CARD)
            btn.bind(on_release=lambda x, n=r_name: self.set_region(n))
            self.reg_btns[r_name] = btn
            region_grid.add_widget(btn)
        self.root.add_widget(region_grid)

        # 3. SYSTEME
        preset_grid = GridLayout(cols=2, size_hint_y=None, height=dp(85), spacing=dp(5))
        self.pre_btns = {}
        for name in ["6aus49", "EUROJACKPOT", "FREIHEIT+", "GLÜCKSSPIRALE"]:
            btn = Button(text=name, font_size=sp(11), background_color=CLR_CARD, bold=True)
            btn.bind(on_release=lambda x, n=name: self.apply_preset(n))
            self.pre_btns[name] = btn
            preset_grid.add_widget(btn)
        self.root.add_widget(preset_grid)

        # 4. EXPERT INPUTS
        self.expert_section = BoxLayout(orientation='vertical', size_hint_y=None, height=0, opacity=0)
        self.inputs = [TextInput(text="49", multiline=False, input_type='number', background_color=(0.1, 0.1, 0.2, 1), foreground_color=CLR_GOLD) for _ in range(7)]
        for ti in self.inputs: self.expert_section.add_widget(ti)
        self.root.add_widget(self.expert_section)

        self.root.add_widget(Label(size_hint_y=1))

        # 5. KUGELN & QRNG LED
        self.ball_row = BoxLayout(size_hint_y=None, height=dp(60), spacing=dp(5))
        self.ball_labels = [Label(text="?", font_size=sp(24), bold=True, color=(0.3, 0.3, 0.3, 1)) for _ in range(7)]
        for lbl in self.ball_labels: self.ball_row.add_widget(lbl)
        self.root.add_widget(self.ball_row)

        status_box = BoxLayout(size_hint_y=None, height=dp(30))
        self.qrng_light = Label(text="•", font_size=sp(45), size_hint_x=None, width=dp(40), color=CLR_RED)
        self.status_label = Label(text="Bereit.", color=CLR_ACCENT, bold=True)
        status_box.add_widget(self.qrng_light); status_box.add_widget(self.status_label)
        self.root.add_widget(status_box)

        # 6. HISTORIE & BUTTONS
        self.hist_label = Label(text="", size_hint_y=0.15, font_size=sp(11), color=(0.5, 0.5, 0.5, 1))
        self.root.add_widget(self.hist_label)

        btn_row = BoxLayout(size_hint_y=None, height=dp(65), spacing=dp(10))
        self.start_btn = Button(text="START", background_color=CLR_ACTIVE, bold=True)
        self.start_btn.bind(on_release=self.start_draw)
        karma_btn = Button(text="KARMA", background_color=CLR_RED, bold=True)
        karma_btn.bind(on_release=self.open_karma)
        btn_row.add_widget(self.start_btn); btn_row.add_widget(karma_btn)
        self.root.add_widget(btn_row)

        Clock.schedule_once(self.ui_refresh, 0.1)
        return self.root

    def ui_refresh(self, dt):
        for name, btn in self.reg_btns.items():
            btn.background_color = CLR_ACTIVE if btn.state == 'down' else CLR_CARD
        for name, btn in self.pre_btns.items():
            btn.background_color = CLR_ACTIVE if self.current_preset == name else CLR_CARD

    def kill_kb(self):
        Window.release_all_keyboards()
        for ti in self.inputs: ti.focus = False

    def set_region(self, name):
        self.kill_kb()
        self.current_region = name
        self.ui_refresh(0)

    def apply_preset(self, name):
        self.kill_kb()
        self.current_preset = name
        for i, v in enumerate(LOTTO_PRESETS[name]): self.inputs[i].text = v
        self.ui_refresh(0)

    def toggle_expert(self, instance):
        self.kill_kb()
        self.expert_section.height = dp(260) if instance.state == 'down' else 0
        self.expert_section.opacity = 1 if instance.state == 'down' else 0

    def start_draw(self, *args):
        self.kill_kb()
        if not self.is_drawing:
            self.qrng_light.color = CLR_RED
            self.status_label.text = "Quanten-Pool wird geladen..."
            self.quantum_success = True
            threading.Thread(target=self.run_logic).start()

    def run_logic(self):
        self.is_drawing = True
        res = []
        for i in range(7):
            lim = int(self.inputs[i].text) if self.inputs[i].text.isdigit() else 49
            pool = list(range(1, lim+1)) if self.current_preset != "GLÜCKSSPIRALE" else list(range(10))

            while True:
                val = self.get_q(pool)
                if self.current_preset == "EUROJACKPOT":
                    if i < 5 and val not in res[:5]: break
                    if i >= 5 and val not in res[5:]: break
                elif self.current_preset == "GLÜCKSSPIRALE":
                    break
                else:
                    if val not in res: break

            res.append(val)
            Clock.schedule_once(lambda dt, idx=i, v=val: self.update_ball(idx, v))
            time.sleep(0.15)

        time.sleep(0.8)
        Clock.schedule_once(self.finalize_draw)

    def update_ball(self, idx, v):
        lbl = self.ball_labels[idx]
        lbl.text = str(v)
        if (self.current_preset == "6aus49" and idx == 6) or (self.current_preset == "EUROJACKPOT" and idx >= 5):
            lbl.color = CLR_GOLD
        else:
            lbl.color = CLR_ACCENT

    def finalize_draw(self, dt):
        if self.quantum_success:
            self.qrng_light.color = CLR_GREEN
            q_tag = " (Q)"
            self.status_label.text = "Quanten-Kombination verifiziert"
        else:
            self.qrng_light.color = CLR_RED
            q_tag = ""
            self.status_label.text = "Ziehung beendet (Lokal)"

        self.hist_label.text = f"{datetime.now().strftime('%H:%M')} | {' . '.join(map(str, [l.text for l in self.ball_labels]))}{q_tag}\n" + self.hist_label.text
        self.is_drawing = False

    def get_q(self, pool):
        try:
            r = requests.get("https://qrng.anu.edu.au/API/jsonI.php?length=1&type=uint8", timeout=2.5)
            data = r.json()
            return pool[data['data'][0] % len(pool)]
        except:
            self.quantum_success = False
            return secrets.choice(pool)

    def open_karma(self, instance):
        self.kill_kb()
        p = random.choice(SPENDEN_PROJEKTE.get(self.current_region))
        webbrowser.open(p[1])

if __name__ == '__main__':
    QuantumLottoKarmaApp().run()'''

with open('main.py', 'w') as f:
    f.write(kivy_code)

print('main.py wurde mit dem Update aktualisiert.')

